### ISSUE TITLE
during json_rec:to_json call, library crash saying "module cound not be loaded", it is looking for #is-record-.

### ISSUE THREAD

**Issue by edwardt** [justinkirby/json_rec#11]
but example does not show is_record is required to make this work?
What is going on?

**Comment by edwardt** [comment]
line 190 in json_rec.erl

**Comment by justinkirby** [comment]
There are specific interface requirements that your module must meet. See https://github.com/justinkirby/json_rec/blob/master/src/json_rec_model.example

Your module is missing the exprecs -compile and -export_records.

**Comment by edwardt** [comment]
Thanks
