### ISSUE TITLE
json_rec.app.src errors

### ISSUE THREAD

**Issue by ddosia** [justinkirby/json_rec#3]
I am trying to integrate this library into my application, and one problem i faced is I unable to create release with reltool whe nI add this library to dependency list.

During further investigations I found several issues with `json_rec.app.src`:

1 `vsn` section possible misconfigured:

``` erlang
...
{vsn, git}, % now
{vsn, "0.0.1"}, % should be something like this
...
```

`app` docs says that vsn is `{vsn, Vsn}`, where `Vsn` is `string()`

2 `applications` section miss `parse_trans`

``` erlang
{applications, [ kernel, stdlib ]} % now
{applications, [ kernel, stdlib, parse_trans ]} % should be
```

3 And the las major issue, which was real problem is:

```
{mod, []} % now,
% must be empty if there is no any active mods
```

Here from erlang docs:

 mod:
           Specifies the application callback module and a start argument, see application(3).

```
       The mod key is necessary for an application implemented as a supervision tree, or the application controller will not know how to start it. The mod key can be omitted for
       applications without processes, typically code libraries such as the application STDLIB.
```

Here stack trace of original issue:

``` erlang
{"init terminating in do_boot",{{case_clause,[]},[{reltool_server,refresh_app,3,[{file,"reltool_server.erl"},{line,1020}]},{reltool_server,refresh_apps,5,[{file,"reltool_server.erl"},{line,1912}]},{reltool_server,refresh,1,[{file,"reltool_server.erl"},{line,1608}]},{reltool_server,do_init,1,[{file,"reltool_server.erl"},{line,155}]},{reltool_server,init,1,[{file,"reltool_server.erl"},{line,133}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,227}]}]}}
```

Erlang version is `R15B02`

**Comment by ddosia** [comment]
If you not mid I could send you PR. It could be spitted to several commits or one with all fixes

**Comment by justinkirby** [comment]
I would love a PR. 

However, this does assume rebar and having {vsn, git} is a feature of rebar that uses the git commit hash as the vsn.  Is your version of rebar not doing this for you?

**Comment by ddosia** [comment]
@justinkirby possible it does, it was just my way to find a problem (to fix all thing in .app file which is not satisfy to specs). I will check this `{vsn, git}` thing later and let you know.

**Comment by ddosia** [comment]
just checked, `{vsn, git}` is substituted properly.

**Comment by justinkirby** [comment]
Daniil Churikov notifications@github.com writes:

> just checked, `{vsn, git}` is substituted properly.

Awesome, glad to here it.
